spring:
  application:
    name: wms
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: nbsdev1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10분
      cache-null-values: false
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# 로깅 설정
logging:
  level:
    root: INFO
    com.wms: DEBUG
    org.hibernate.SQL: DEBUG
